### ISSUE TITLE
How i can list unspent transaction for any private key of address.

### ISSUE THREAD

**Issue by coingeek** [Bit-Wasp/bitcoin-lib-php#86]
How i can list unspent transaction for any private key of address.
is there any idea.

**Comment by afk11** [comment]
You need to get that data for yourself. Either use bitcoind with watchonlyaddress, or keep the key in bitcoind (bad idea if you put this on a webserver), or use an API to look it up.

It's beyond the scope of this library, since consumers needs are going to vary a lot. 

Bitcoin is tricky to get right, but I'd search https://bitcointalk.org (Technical Development) or https://bitcoin.stackexchange.com, the odds are someone has answered the question already!

**Comment by rubensayshi** [comment]
**shameless plug for my own product**

@coingeek you could use an API like ours to get the unspents for the address corresponding to the private key: https://www.blocktrail.com/api/docs#api_address_unspent

**Comment by btcdrak** [comment]
If you want to get unspent outputs for any address, you can use the addrindex patched version of bitcoind at https://github.com/btcdrak/bitcoin/releases

**Comment by rubensayshi** [comment]
@btcdrak he's trying to get his altcoin (litecoin fork) to work ... :(

**Comment by btcdrak** [comment]
he can merge the addrindex patch then ;)

**Comment by coingeek** [comment]
@btcdrak 
how I can merge it, or how i can add it to my altcoin?
